In [1]:
import numpy as np

In [ ]:
## Задание 1.

In [ ]:
## Задача 1. Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [2]:
a = np.random.randint(0, 20, 10)

In [3]:
a

array([ 7, 19, 12,  5, 10,  1,  1, 16,  3, 18])

In [6]:
a[(a>3)&(a<8)]*(-1)

array([], dtype=int32)

In [7]:
a

array([-7, 19, 12, -5, 10,  1,  1, 16,  3, 18])

In [ ]:
## Задача 2. Заменить максимальный элемент случайного массива на 0 

In [8]:
x  = np.random.randint(0, 20, 10)

In [9]:
x

array([13, 13,  8,  6,  1,  8,  7,  2,  5, 18])

In [10]:
m=np.argmax(x)
x[m]= 0

In [11]:
x

array([13, 13,  8,  6,  1,  8,  7,  2,  5,  0])

In [ ]:
## Задача 3. Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [13]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [ ]:
## Задача 4. Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [16]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))


In [17]:
A

array([[3, 3, 4],
       [4, 4, 4],
       [1, 3, 2],
       [2, 0, 4],
       [4, 4, 3],
       [3, 3, 0],
       [3, 1, 0],
       [2, 4, 3]])

In [18]:
B

array([[1, 1],
       [2, 2]])

In [19]:
C = (A[..., np.newaxis, np.newaxis] == B)

In [20]:
result = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]

In [21]:
result

array([2, 3, 6, 7], dtype=int64)

In [ ]:
## Задача 5. Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [23]:
n = np.array([
    [1, 1, 1],  
    [2, 2, 3],  
    [4, 4, 4],  
    [5, 6, 5], 
    [7, 7, 7],  
    [8, 9, 10], 
    [1, 1, 1],  
    [2, 3, 2], 
    [4, 4, 4],  
    [5, 5, 6]  
])

In [24]:
n

array([[ 1,  1,  1],
       [ 2,  2,  3],
       [ 4,  4,  4],
       [ 5,  6,  5],
       [ 7,  7,  7],
       [ 8,  9, 10],
       [ 1,  1,  1],
       [ 2,  3,  2],
       [ 4,  4,  4],
       [ 5,  5,  6]])

In [25]:
 m = n[(n[:,1]!=n[:,0]) | (n[:,2]!=n[:,0])]

In [26]:
m

array([[ 2,  2,  3],
       [ 5,  6,  5],
       [ 8,  9, 10],
       [ 2,  3,  2],
       [ 5,  5,  6]])

In [ ]:
## Задача 6. Дан двумерный массив. Удалить те строки, которые повторяются

In [28]:
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],
    [7, 8, 9],
    [4, 5, 6]] )


In [29]:
c = np.unique(b, axis=0)

In [30]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
## Задание 2:

In [ ]:
## Задача 1: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.
Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [31]:
X = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
result =1
for i in range(0,min(len(X),len(X[0]))):
    if(X[i][i]):
        result*=X[i][i]

result

3

In [32]:
## Вариант с Np

In [34]:
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
result = np.prod(np.diag(X)[np.diag(X) != 0])
result

3

In [ ]:
## Задача 2: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.
##Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [36]:
x = [1, 2, 3, 4]
y = [4, 3, 1, 2]
sorted(x) == sorted(y)

True

In [ ]:
## Вариант с Np

In [37]:
x = np.array([1, 2, 3, 4])
y = np.array([4, 3, 1, 2])
np.array_equal(np.sort(x), np.sort(y))

True

In [ ]:
## Задача 3: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль.
## Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [38]:
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
y = [x[i+1] for i in range(len(x) - 1) if x[i] == 0 ]
max(y)

5

In [ ]:
## Вариант с Np

In [40]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
x[1:][x[:-1]==0].max()

5

In [ ]:
## Задача 4: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.
## Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [47]:
from collections import Counter

In [50]:
from collections import Counter

x = [2, 2, 2, 3, 3, 3, 5]
c = Counter(x)
print(c.keys(), c.values())

dict_keys([2, 3, 5]) dict_values([3, 3, 1])


In [ ]:
## Вариант с Np

In [42]:
x = np.array([2, 2, 2, 3, 3, 3, 5])
np.unique(x,return_counts=True)

(array([2, 3, 5]), array([3, 3, 1], dtype=int64))

In [ ]:
## Задача 5: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами.
## Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [76]:

a = np.array((3, 2, 1))
b = np.array((3, 0, 2))

from math import *
distance = np.sqrt(sum(pow(a-b, 2) for a, b in zip(point_1, point_2)))
print(distance)

2.23606797749979


In [66]:
## Вариант с Np

In [70]:
distance = np.linalg.norm(a-b)
distance

2.23606797749979

In [ ]:
## Задание 3:


In [ ]:
## Задание 1. Просмотрите файл cereal.csv.
## Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [59]:
calorie_stats = np.loadtxt("./Downloads/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

In [ ]:
## Задание 2.В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

In [61]:
average_calories = round(np.mean(calorie_stats) - 60,2)
average_calories

46.88

In [ ]:
## Задание 3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.
## Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [62]:
calorie_stats_sorted = np.sort(calorie_stats)
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

In [ ]:
## Задание 4.Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.
## Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [63]:
median_calories = np.median(calorie_stats)
median_calories

110.0

In [ ]:
## Задание 5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.
## Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [64]:
nth_procentile = 0
while np.percentile(calorie_stats,nth_procentile)<=60:
    print( np.percentile(calorie_stats,nth_procentile))
    nth_procentile+=1
nth_procentile

50.0
50.0
50.0
55.599999999999994


4

In [71]:
## Задание 6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.
## Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [72]:
more_calories = len(calorie_stats[calorie_stats>60])/len(calorie_stats)*100
more_calories

96.1038961038961

In [ ]:
## Задание 7 Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?
## Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [73]:
calorie_std = np.std(calorie_stats)
calorie_std

19.35718533390827

In [ ]:
## Задание 8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [74]:
'''' На основании полученных данных, 96% остальных производителей содержат больше калорий, причем содержат их в среднем на 75% больше. Медиана содержания калорий находится на отметке в 110 калорий, что почти в два раза больше, чем в CrunchieMunchies. Большая же часть производителей отклоняется от этой отметки не более, чем на 20 калорий'''

"' На основании полученных данных, 96% остальных производителей содержат больше калорий, причем содержат их в среднем на 75% больше. Медиана содержания калорий находится на отметке в 110 калорий, что почти в два раза больше, чем в CrunchieMunchies. Большая же часть производителей отклоняется от этой отметки не более, чем на 20 калорий"